# Allows at most 5 submissions per user per period, where period is 24 hours by default.
max_submissions_per_period: 5
refresh_period_seconds: 1

# UUID of the worksheet where prediction and evaluation bundles are created for submissions.
log_worksheet_uuid: '0x39d3c5952de34856a1414d01bb62d7d9'    

# Configure the tag that participants use to submit to the competition.
# In this example, any bundle with the tag `some-competition-submit` would be
# considered as an official submission.
submission_tag: data-centric-submission

# Configure how to mimic the submitted prediction bundles. When evaluating a submission, 
# `new` bundle will replace `old` bundle.
# For a machine learning competition, `old` bundle might be the dev set and `new` bundle
# might be the hidden test set.
predict:
  mimic:
  - {new: '0xee7f0298b3f74d6b86167422e3d2eafe', old: '0xdf394cc2d2b94e60a7c8c79cb3474916'}
  tag: data-centric-predict

# Configure how to evaluate the new prediction bundles.
# In this example, evaluate.py is script that takes in the paths of the test labels and 
# predicted labels and outputs the evaluation results.
evaluate:
  # Essentially
  #     cl run evaluate.py:0x089063eb85b64b239b342405b5ebab57 \
  #            test.json:0x5538cba32e524fad8b005cd19abb9f95 \
  #            predictions.json:{predict}/predictions.json --- \
  #            python evaluate.py test.json predictions.json
  # where {predict} gets filled in with the uuid of the mimicked bundle above.
  dependencies:
  - {child_path: evaluate.py, parent_uuid: '0x1bd0f992d81248e2a7e94f6f84ccedc5'}
  - {child_path: data.json, parent_uuid: '0x1a0cf934fe7a498d99914e5f466e1a90'}
  - {child_path: predictions.json, parent_uuid: '{predict}'}
  command: python evaluate.py predictions.json data.json
  tag: data-centric-eval

# Define how to extract the scores from the evaluation bundle.
# In this example, result.json is a JSON file outputted from the evaluation step
# with F1 and exact match metrics (e.g. {"f1": 91, "exact_match": 92}).
score_specs:
- {key: '/result.json:accuracy', name: accuracy}